Repository mapshare/map-share-frontend, pull requests merged in 2019-05, with the labels that each got.

#10 [MSW-#9] clean up reviews and restaurants components
  src/actions/reviewActions.js
  src/components/RestaurantComponents/AddRestaurant.js
  src/components/RestaurantComponents/RestaurantDetails.js
  src/components/ReviewComponents/PostReview.js
  src/components/ReviewComponents/PutReview.js
  src/reducers/reviewReducer.js
Labels: Clean up

#12 [MSW-11] Clean up SignInForm & GroupLanding Components
  src/components/AuthContainer/AuthContainer.scss
  src/components/GroupLanding/GroupLanding.js
  src/components/GroupLanding/GroupLanding.scss
  src/components/SignInForm/SignInForm.js
  src/components/SignInForm/SignInForm.scss
  src/data/constants.js
Labels: Clean up

#13 [MSW-7] Change redux key to constant values
  src/actions/groupActions.js
  src/actions/marksActions.js
  src/actions/restaurantActions.js
  src/actions/reviewActions.js
  src/actions/signInActions.js
  src/data/key.js
  src/reducers/marksReducer.js
  src/reducers/restaurantsReducer.js
  src/reducers/reviewReducer.js
  src/reducers/signInReducer.js
Labels: Redux

#18 [MSW-17] fix reviewId undefined for updating review
  src/components/RestaurantComponents/RestaurantDetails.js
  src/components/ReviewComponents/PutReview.js
Labels: bug

#22 MSF-11 Refactored reducers
  src/components/MapBoxContainer/MapBoxContainer.js
  src/components/MapContainer/MapContainer.js
  src/components/Markers/Markers.js
  src/components/RestaurantComponents/AddRestaurant.js
  src/components/RestaurantComponents/RestaurantDetails.js
  src/components/ReviewComponents/PostReview.js
  src/components/ReviewComponents/PutReview.js
  src/reducers/marksReducer.js
  src/reducers/reviewReducer.js
  src/reducers/rootReducer.js
Labels: Redux
